service: ebot7-facebook-integration

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  # e-bot7 Applications work with any framework and cloud provider
  # These examples use Serverless, Node, and AWS Lambdas
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
functions:
  # Handles events sent by ebot7 Application Platform
  # The URL of this endpoint will be provided as Events endpoint
  eventsEndpoint:
    handler: handler.eventsEndpoint
    events:
        - http:
            method: post
            path: events
  redirectEndpoint:
    handler: handler.redirectEndpoint
    events:
        - http:
            method: get
            path: redirect
